options:
  backLink: 'Back to main page'
  brandNames:
    desktop: 'Wobble API Documentation'
    tablet: 'Wobble API Docs'
    mobile: 'API Docs'
  brandClasses: 'fill-red'

languages:
  - title: 'cURL'
    short: 'cURL'
    value: 'curl'
  - title: 'CLI'
    short: 'cli'
    value: 'cli'
  - title: 'Python'
    short: 'Python'
    value: 'python'
  - title: 'JavaScript'
    short: 'JS'
    value: 'javascript'
  - title: 'Java'
    short: 'Java'
    value: 'java'
  - title: 'Objective-C'
    short: 'ObjC'
    value: 'objc'
  - title: 'Swift'
    short: 'Swift'
    value: 'swift'

menu:
  - section: '# Introduction'
    file: introduction.md
  - section: '# Example'
    file: example.md